name: Example NuGet Publish with Approval

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: write
  workflows: write

jobs:
  publish-nuget:
    name: Publish NuGet with Approval
    uses: ./.github/workflows/publish-nuget.yml
    with:
      source-workflow-name: "ci-dotnet.yml"
      environment: "nuget-production"
      artifact-name: "release-packages"
    secrets:
      NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
