name: testproject/archiduct

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

on:
  pull_request:
    branches:
      - main

jobs:
  all:
    name: Build & Tests
    uses: ./.github/workflows/build-dotnet-matrix.yml
    with:
      disableTestsOnWindows: true
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      dotnetQuality: ${{ vars.NE_DOTNET_QUALITY }}
      enableCleanUpDockerDocker: false
      solution: ./testprojects/archiduct/ArchiDuct.sln
    secrets: inherit