name: Run PR against `testproject/healthchecks`

on:
  pull_request:
    branches:
      - main

jobs:
  all:
    name: Build & Tests - `testproject/healthchecks`
    uses: ./.github/workflows/build-dotnet-single.yml
    with:
      disableCodeQL: true
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      dotnetQuality: ${{ vars.NE_DOTNET_QUALITY }}
      enableCleanUpDockerDocker: true
      solution: ./testprojects/healthchecks/HealthChecks.sln