name: testproject/hosting.winforms

permissions:
  actions: read
  contents: read
  pull-requests: write
  security-events: write

on:
  pull_request:
    branches:
      - main

jobs:
  all:
    name: Build & Tests
    uses: ./.github/workflows/build-dotnet-single.yml
    with:
      disableCodeFormat: true
      dotnetVersion: ${{ vars.NE_DOTNET_TARGETFRAMEWORKS }}
      dotnetQuality: ${{ vars.NE_DOTNET_QUALITY }}
      enableCleanUpDockerDocker: true
      runsOnBuild: windows-latest
      solution: ./testprojects/hosting.winforms/Extensions.Hosting.WinForms.sln
    secrets: inherit