on:
  workflow_call:
    inputs:
      dotnet-logging:
        required: false
        type: string
        default: quiet
      dotnet-version:
        required: false
        type: string
        default: 8.x
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      FETCH_TOKEN:
        required: false

defaults:
  run:
    shell: pwsh

permissions:
  contents: read

jobs:
  format:
    name: Validate Code Formatting
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.FETCH_TOKEN || github.token }}

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        global-json-file: ./global.json

    - name: Install CSharpier
      run: |
        dotnet tool install --global csharpier

    - name: Linting solution
      run: |
        csharpier check .
