on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      solution-version:
        required: true
        type: string
    secrets:
      FETCH_TOKEN:
        required: false

permissions:
    contents: write
    pull-requests: write

jobs:
  draft-release:
    name: Create Release
    if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.FETCH_TOKEN || github.token }}

    - name: Release Drafter
      uses: release-drafter/release-drafter@693d20e7c1ce1a81d3a41962f85914253b518449 # v7.3.1
      with:
        version: ${{ inputs.solution-version }}
        publish: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
