on:
  workflow_call:
    inputs:
      dotnet-version:
        required: false
        type: string
        default: 8.x
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      FETCH_TOKEN:
        required: false
    outputs:
      solution-version:
        description: 'The repository version, based on git history'
        value: ${{ jobs.detect-version.outputs.version }}

permissions:
  contents: read

jobs:
  detect-version:
    name: Detect Version
    runs-on: ${{ inputs.runs-on || 'ubuntu-latest' }}

    outputs:
      version: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
        submodules: recursive
        token: ${{ secrets.FETCH_TOKEN || github.token }}

    - name: Setup .NET
      uses: actions/setup-dotnet@c2fa09f4bde5ebb9d1777cf28262a3eb3db3ced7 # v5.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        global-json-file: ./global.json

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@e0d584e657c606912e8fd522aeed29025975705f # v4.4.2
      with:
        versionSpec: '6.x'

    - name: Determine Version
      id:   gitversion
      uses: gittools/actions/gitversion/execute@e0d584e657c606912e8fd522aeed29025975705f # v4.4.2